INSERT INTO resort (name, nick, latitude, longitude, widget_id, ots_url, website) VALUES ('Crystal Mountain Resort', 'Crystal', 46.92332964, -121.475998096, 124, 'https://www.onthesnow.com/washington/crystal-mountain-wa/skireport.html', 'http://crystalmountainresort.com/');
INSERT INTO resort (name, nick, latitude, longitude, widget_id, ots_url, website) VALUES ('Vail Ski Resort', 'Vail', 39.6391, -106.3738, 482, 'https://www.onthesnow.com/colorado/vail/skireport.html','https://www.vail.com/');
INSERT INTO resort (name, nick, latitude, longitude, widget_id, ots_url, website) VALUES ('Stevens Pass Resort', 'Stevens', 47.74499702, -121.09333296, 427, 'https://www.onthesnow.com/washington/stevens-pass-resort/skireport.html','https://www.stevenspass.com/site');
INSERT INTO resort (name, nick, latitude, longitude, widget_id, ots_url, website) VALUES ('Yosemite Ski & Snowboard Area', 'Yosemite', 37.6622677, -119.6633655, 29, 'https://www.onthesnow.com/california/badger-pass/skireport.html','https://www.yosemite.com/yosemite/yosemite-westbadger-pass/');
INSERT INTO resort (name, nick, latitude, longitude, widget_id, ots_url, website) VALUES ('Mammoth Mountain Ski Area', 'Mammoth', 37.630768, -119.7175, 227, 'https://www.onthesnow.com/california/mammoth-mountain-ski-area/skireport.html','https://www.mammothmountain.com/winter/mountain-information/mountain-information');
INSERT INTO resort (name, nick, latitude, longitude, widget_id, ots_url, website) VALUES ('Whistler Blackcomb', 'Whistler', 50.116322, -122.957359, 493, 'https://www.onthesnow.com/british-columbia/whistler-blackcomb/skireport.html','https://www.whistlerblackcomb.com/');
INSERT INTO resort (name, nick, latitude, longitude, widget_id, ots_url, website) VALUES ('Park City Mountain Resort', 'Park City', 40.646061, -111.497971, 314, 'https://www.onthesnow.com/utah/park-city-mountain-resort/skireport.html','https://www.parkcitymountain.com/');
INSERT INTO resort (name, nick, latitude, longitude, widget_id, ots_url, website) VALUES ('The Summit at Snoqualmie', 'Snoqualmie', 47.4248345, -121.4184276, 466, 'https://www.onthesnow.com/washington/the-summit-at-snoqualmie/skireport.html','https://summitatsnoqualmie.com/');
INSERT INTO resort (name, nick, latitude, longitude, widget_id, ots_url, website) VALUES ('Mount Baker', 'Mt. Baker', 48.8584576, -121.6770853, 266, 'https://www.onthesnow.com/washington/mt-baker/skireport.html','https://www.mtbaker.us/');

